[datasets]
replogle_h1 = "/raid/kreid/v_cell/competition_support_set/{competition_train,k562_gwps,rpe1,jurkat,k562,hepg2}.h5"

[training]
replogle_h1 = "train"

[zeroshot]

[fewshot]
[fewshot."replogle_h1.ARC_H1"]
val = [ "ACAT2", "ARID1A", "ATP6V0C", "CLDN6", "CLDN7", "ETV4", "HDAC8", "HTATSF1", "IDE", "INSIG1", "JAZF1", "JMJD8", "KDM2B", "KLF10", "LZTR1", "MAP3K7", "MAT2A", "MED1", "METTL14", "NDUFB4", "PHF14", "RNF20", "SLC25A3", "SMAGP", "SMARCB1", "SSBP1", "TCF3", "USF2", "WAC", "ZNF714",]
test = [ "ACLY", "BRD9", "C1QBP", "CAST", "CENPB", "CENPO", "COX4I1", "DHCR24", "GNG12", "IKBKG", "KAT2A", "KDM1A", "KLHDC2", "MAPKAPK2", "MED12", "MED13", "METTL3", "MGST1", "MTFR1", "NIT1", "OXA1L", "PMS1", "PRDM14", "RAF1", "SALL4", "SMARCA4", "TARBP2", "TET1", "UQCRB", "ZNF581",]
